
# POST DATA TO ADD ADMIN 
POST http://localhost:5000/public/admin/register
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "mobile": "9876543210",
    "password": "12345",
}

###

# LOGIN ADMIN
POST http://localhost:5000/public/admin/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "12345"
}
###
# ADD DOCTOR
POST http://localhost:5000/public/admin/add-doctor
Content-Type: application/json

{
    "name": "Dr. Jane Doe",
    "email": "janedoe@gmail.com",
    "password": "12345",
    "mobile": "9876543210",
    "designation": "Senior",
    "department": "Cardiologist",
    "type": "contractual",
    "dutyHoursPerMonth": 180,
    "dutyHoursPerDay": 8
}

###
# Update doctor
PUT http://localhost:5000/public/admin/update-doctor
Content-Type: application/json

{
    "email": "janedoe@gmail.com",
    "dutyHoursPerMonth": "180",
    "dutyHoursPerDay": "8 hrs"
}
###
# ADD BREAK
POST http://localhost:5000/public/admin/add-breaks
Content-Type: application/json

{
    "breakName" : "Lunch Break",
    "startTime": "1:00 PM",
    "endTime": "2:00 PM",
    "breakDuration": "1 hr",
    "breakType": "Automatic",
    "breakStatus": true
}

###
# GET BREAK
GET http://localhost:5000/public/admin/get-all-breaks
Content-Type: application/json

###
# DELETE BREAK
POST http://localhost:5000/public/admin/delete-break
Content-Type: application/json

{
    "breakName": "Lunch Break"
}

###
#UPDATE BREAK STATUS
PUT http://localhost:5000/public/admin/update-break-status
Content-Type: application/json

{
    "breakName": "Lunch Break",
    "breakStatus": false
}

###
#GET LEAVES
GET http://localhost:5000/public/admin/get-all-leaves
Content-Type: application/json
