POST http://localhost:5000/private/shift/generate-shift
Content-Type: application/json

{   "domain":"echo",
    "startDate": "2023-01-22",
    "endDate": "2023-01-31"
}

###

POST http://localhost:5000/private/shift/generate-calendar
Content-Type: application/json

{
    "currentMonth": 11
}
###
GET http://localhost:5000/private/shift/get-shifts-by-domain?domain=echo
Content-Type: application/json

###

# get calender by current month

GET http://localhost:5000/private/shift/get-calendar?currentMonth=0
Content-Type: application/json

###
POST http://localhost:5000/private/shift/add-slot
Content-Type: application/json

{
    "slotTime": "11:00 PM - 12:00 AM",
    "isNight": true
}

###
# SHIFT REPLACMENT
POST http://localhost:5000/private/shift/shift-replace
Content-Type: application/json

{
    "name": "Dr. Shaan Sharma",
    "replacement": "Vineesh",
    "date": "2/1/2023",
    "start": "10:00 AM",
    "end": "1:00 PM"
}

###
#SHIFT REPLACEMENT REQUESTS
GET http://localhost:5000/private/shift/get-shift-replace-requests
Content-Type: application/json
###

# UPDATE SHIFT
PUT http://localhost:5000/private/shift/update-shift/63ceaf6774df67649df7eb55
Content-Type: application/json

{
    "doctors":[ "63a95a79827a4f6c6af5823c","63a9ad9ec4ccdb71c8b3ced9","63aa9aaa793231a75de33fcd"]
}

###
# CREATE SHIFT
POST http://localhost:5000/private/shift/create-shift
Content-Type: application/json

{
    "doctors":[ "63b15b0cf6343140d174e29e","63b15a043727fad53543b77e","63aa9aaa793231a75de33fcd"],
    "shiftDate": "2023-01-02",
    "shiftDay": "Monday",
    "shiftTime": "10:00 AM - 11:00 AM",
    "shiftDomain": "echo",
    "slotId": "63ad32897c917d598f58dc6a"
}