POST http://localhost:5000/private/shift/generate-shift
Content-Type: application/json

###

POST http://localhost:5000/private/shift/generate-calendar
Content-Type: application/json

{
    "currentMonth": 9
}

###

# get calender by current month

GET http://localhost:5000/private/shift/get-calendar?currentMonth=11
Content-Type: application/json

###
POST http://localhost:5000/private/shift/add-slot
Content-Type: application/json

{
    "slotTime": "07:00 PM - 08:00 PM",
    "isNight": false
}

###

# update slot

PUT  http://localhost:5000/private/shift/update-slot
Content-Type: application/json

{
    "Allotment":[
        {
            "DoctorsNeeded": 2,
            "SeniorNeeded": 0,
            "day": "Sunday"
        }
    ],
    "slotTime": "08:00 PM - 09:00 PM"
}

###
# update slot

PUT  http://localhost:5000/private/shift/update-slot
Content-Type: application/json

{
    "Allotment":[
        {
            "DoctorsAlloted": 0,
            "isFulfilled": false,
            "day": "Wednesday"
        }
    ],
    "slotTime": "07:00 PM - 08:00 PM"
}

###

# update all slot

PUT  http://localhost:5000/private/shift/update-all-slots
Content-Type: application/json

{
    "Allotment":[
        {
            "DoctorsAlloted": 0,
            "isFulfilled": false,
            "day": "Wednesday"
        }
    ]
}
###
# delete all shifts

DELETE http://localhost:5000/private/shift/delete-all-shifts
Content-Type: application/json

###
# get all slots

GET http://localhost:5000/private/shift/get-all-slots
Content-Type: application/json

###
# SHIFT REPLACMENT
POST http://localhost:5000/private/shift/shift-replace
Content-Type: application/json

{
    "name": "Dr. Shaan Sharma",
    "replacement": "Vineesh",
    "date": "2/1/2023",
    "start": "10:00 AM",
    "end": "1:00 PM"
}