POST http://localhost:5000/private/shift/generate-shift
Content-Type: application/json

###

POST http://localhost:5000/private/shift/generate-calendar
Content-Type: application/json

{
    "currentMonth": 9
}

###
// 06:00 AM - 07:00 AM", "07:00 AM - 08:00 AM", "08:00 AM - 09:00 AM", "09:00 AM - 10:00 AM",
// "10:00 AM - 11:00 AM", "11:00 AM - 12:00 PM", "12:00 PM - 01:00 PM", "01:00 PM - 02:00 PM", "02:00 PM - 03:00 PM",
// "03:00 PM - 04:00 PM", "04:00 PM - 05:00 PM", "05:00 PM - 06:00 PM", "06:00 PM - 07:00 PM", "07:00 PM - 08:00 PM",
// "08:00 PM - 09:00 PM", "09:00 PM - 10:00 PM", "10:00 PM - 11:00 PM", "11:00 PM - 12:00 AM
POST http://localhost:5000/private/shift/add-slot
Content-Type: application/json

{
    "slotTime": "11:00 PM - 12:00 AM",
    "isNight": false
}