
# update slot

PUT  http://localhost:5000/private/slot/update-slot
Content-Type: application/json

{
    "Allotment":[
        {
            "DoctorsNeeded": 2,
            "SeniorNeeded": 0,
            "day": "Sunday"
        }
    ],
    "slotTime": "08:00 PM - 09:00 PM"
}

###
# update slot

PUT  http://localhost:5000/private/slot/update-slot
Content-Type: application/json

{
    "Allotment":[
        {
            "DoctorsAlloted": 0,
            "isFulfilled": false,
            "day": "Wednesday"
        }
    ],
    "slotTime": "07:00 PM - 08:00 PM"
}

###

# update all slot

PUT  http://localhost:5000/private/slot/update-all-slots
Content-Type: application/json

{
    "Allotment":[
        {
            "DoctorsAlloted": 0,
            "isFulfilled": false,
            "day": "Wednesday"
        }
    ]
}
###
# delete all slots

DELETE http://localhost:5000/private/slot/delete-all-slots
Content-Type: application/json

###
# get all slots

GET http://localhost:5000/private/slot/get-all-slots
Content-Type: application/json

###
# replace date
PUT http://localhost:5000/private/slot/replace-date
Content-Type: application/json

{
    "oldDate": "2023-02-04",
    "newDate": "04"
}