# LOGIN USER
POST http://localhost:5000/public/auth/login
Content-Type: application/json

{
    "email": "vishal@gmail.com",
    "password": "1234"
}

###

# GET USER
GET http://localhost:5000/public/auth/
Content-Type: application/json
###

# RESET PASSWORD

POST http://localhost:5000/public/auth/reset-password/63a9bde9d827d6f6975b4af2
Content-Type: application/json

{
    "password": "1234"
}
###
# SHIFT REPLACMENT
POST http://localhost:5000/public/auth/6395f4b82fb301eb92489e01/shift-replace
Content-Type: application/json

{
    "name": "Dr. Jane Doe",
    "replacement": "Dr. John Doe",
    "date": "22nd December 2022",
    "start": "10:00 AM",
    "end": "1:00 PM"
}

###

# REQUEST SPECIAL
POST http://localhost:5000/public/auth/6399a8b629ae28c5337d382d/special-request
Content-Type: application/json

{
   "request": "He is given a break from 4 PM to 5 PM for Yoga during the month of November"
}
###
# ADD AVAILABILITY
POST http://localhost:5000/public/auth/63a95a79827a4f6c6af5823c/add-availability
Content-Type: application/json

{
    "schedule":[
        {
            "day": "Monday",
            "start": "05:00 PM",
            "end": "10:00 PM"
        },
        {
            "day": "Friday",
            "start": "2:00 AM",
            "end": "8:00 AM"
        }
    ]
}

###

# GET AVAILABILITY
GET http://localhost:5000/public/auth/63a95a79827a4f6c6af5823c/get-availability
Content-Type: application/json
###

# DELETE AVAILABILITY
PUT http://localhost:5000/public/auth/63a95a79827a4f6c6af5823c/delete-availability-by-day
Content-Type: application/json

{
    "day": "Monday"
}
###
# REQUEST LEAVE
POST http://localhost:5000/public/auth/63a95a79827a4f6c6af5823c/request-leave
Content-Type: application/json

{
   
    "leaveType": "casual",
    "leaveReason": "He is going to attend a conference",
     "startDate": "5/12/22",
    "endDate": "7/12/22"
    
}