# LOGIN USER
POST http://localhost:5000/public/auth/login
Content-Type: application/json

{
    "email": "janedoe@gmail.com",
    "password": "12345"
}

###

# GET USER
GET http://localhost:5000/public/auth/
Content-Type: application/json
###

# SHIFT REPLACMENT
POST http://localhost:5000/public/auth/6395f4b82fb301eb92489e01/shift-replace
Content-Type: application/json

{
    "name": "Dr. Jane Doe",
    "replacement": "Dr. John Doe",
    "date": "22nd December 2022",
    "start": "10:00 AM",
    "end": "1:00 PM"
}

###

# ADD AVAILABILITY
POST http://localhost:5000/public/auth/6399a8b629ae28c5337d382d/add-availability
Content-Type: application/json

{
    "schedule":[
        {
            "day": "Monday",
            "start": "05:00 PM",
            "end": "10:00 PM"
        },
        {
            "day": "Thursday",
            "start": "2:00 AM",
            "end": "8:00 AM"
        }
    ]
}

###

# GET AVAILABILITY
GET http://localhost:5000/public/auth/6395f4b82fb301eb92489e01/get-availability
Content-Type: application/json
###

